call plug#begin()
Plug 'airblade/vim-gitgutter'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'fatih/vim-go'
Plug 'jiangmiao/auto-pairs'
Plug 'majutsushi/tagbar'
Plug 'myusuf3/numbers.vim'
Plug 'nanotech/jellybeans.vim'
Plug 'othree/xml.vim'
Plug 'plasticboy/vim-markdown'
Plug 'PProvost/vim-ps1'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
"Plug 'OmniSharp/omnisharp-vim'
call plug#end()

colorscheme jellybeans

if has('gui_running')
    set guifont=Consolas:h8:cANSI
endif

let g:airline_theme='jellybeans'
